// Code generated by mockery v2.13.0-beta.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EventsRepository is an autogenerated mock type for the EventsRepository type
type EventsRepository struct {
	mock.Mock
}

type NewEventsRepositoryT interface {
	mock.TestingT
	Cleanup(func())
}

// NewEventsRepository creates a new instance of EventsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEventsRepository(t NewEventsRepositoryT) *EventsRepository {
	mock := &EventsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
